namespace: mern-devops

frontend:
  replicas: 1
  image: atkaridarshan04/bookstore-frontend:v2
  containerPort: 5173

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  service:
    type: NodePort
    port: 5173
    nodePort: 31000

  config:
    backendUrl: http://192.168.88.133:31100 # Using nodeport service
    # backendUrl: http://192.168.88.133  # after configuring ingress 
    # backendUrl: http://deployzone.duckdns.org # after configuring donain for ingress-ip 


backend: 
  replicas: 1
  image: atkaridarshan04/bookstore-backend:v2
  containerPort: 8000

  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 15

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  service:
    type: NodePort
    port: 8000
    nodePort: 31100


persistentVolume:
  capacity: 1Gi
  accessMode: ReadWriteOnce
  reclaimPolicy: Retain
  storageClassName: manual
  hostPath: "/mnt/data"

persistentVolumeClaim:
  accessMode: ReadWriteOnce
  storage: 1Gi
  storageClassName: manual


mongodb:
  replicas: 1
  image: mongo:4.4

  username: admin
  password: password123
  dbName: db
  
  serviceType: ClusterIP
  serviceName: mongodb-service  # default service name without release name
  authSource: admin