apiVersion: v1 
kind: Service 
metadata: 
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      nodePort: {{ .Values.backend.service.nodePort }}
