# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-ingress
#   namespace: {{ .Values.namespace }}
# spec:
#   ingressClassName: nginx
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Release.Name }}-frontend-service
#                 port:
#                   number: {{ .Values.frontend.containerPort }}
#           - path: /books
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Release.Name }}-backend-service
#                 port:
#                   number: {{ .Values.backend.containerPort }}