apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongodb.username | b64enc }}
  password: {{ .Values.mongodb.password | b64enc }}
