apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mongodb.serviceType }}
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
