apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: mern-devops
data:
  # VITE_API_BACKEND_URL: http://192.168.88.133:31100 # using nodeport service
  #  VITE_API_BACKEND_URL: http://192.168.88.133  # after configuring ingress 
  VITE_API_BACKEND_URL: http://deployzone.duckdns.org # after configuring donain for ingress-ip 

