apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mern-devops
  labels:
    app: frontend
spec:
  # maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: atkaridarshan04/bookstore-frontend:v2
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: frontend-config
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 30
            periodSeconds: 15  
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "0.25"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "0.25"    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-devops
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 31000
