apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-deployment
  namespace: mern-devops
  labels:
    app: mongodb
spec:
  # minAvailable: 2 
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      securityContext:       # Pod-level security context
        runAsNonRoot: true
        runAsUser: 999       # Mongo official container uses 999
        fsGroup: 999         # Ensures volume write access
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "db"
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "0.25"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "0.25"
          volumeMounts:
            - name: mongodb-vol
              mountPath: /data/db
          securityContext:  # Container-level security context
            runAsNonRoot: true
            runAsUser: 999       # Mongo official container uses 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL  # Drop all capabilities for security
      volumes:
        - name: mongodb-vol
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mern-devops
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP