apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-devops
type: Opaque
data:
  username: YWRtaW4=            # base64 encoded for 'admin'
  password: cGFzc3dvcmQxMjM=    # base64 encoded for 'password123'