@Library('Shared-Library') _
pipeline {
    agent {label 'worker-node'}
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    code_checkout("https://github.com/atkaridarshan04/MERN-DevOps.git","main")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }
        
        
        stage("Update: Kubernetes manifests"){
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/bookstore-backend.*/bookstore-backend:${params.BACKEND_DOCKER_TAG}/g backend.yml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/bookstore-frontend.*/bookstore-frontend:${params.FRONTEND_DOCKER_TAG}/g frontend.yml
                        """
                    }
                    
                }
            }
        }
        
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'GitHub', gitToolName: 'Default')]) {
                        sh '''
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Updated environment variables"
                        
                        echo "Pushing changes to github: "
                        git push https://github.com/atkaridarshan04/MERN-DevOps.git main
                    '''
                    }
                }
            }
        }
    }
  post {
    always {
        script {
            emailext(
                attachLog: true,
                from: 'atkaridarshan04@gmail.com',
                subject: "🚀 BookStore Application Deployment Status: '${currentBuild.result}'",
                body: """
                    <html>
                    <body style="font-family: Arial, sans-serif;">
                        <div style="background-color: #FFA07A; padding: 20px; margin-bottom: 15px; border-radius: 10px;">
                            <h2 style="color: black; font-weight: bold; text-align: center;">📦 Project Update</h2>
                            <p style="color: black; font-size: 16px; text-align: center;">
                                <strong>Project:</strong> ${env.JOB_NAME}
                            </p>
                        </div>

                        <div style="background-color: #90EE90; padding: 20px; margin-bottom: 15px; border-radius: 10px;">
                            <h3 style="color: black; font-weight: bold; text-align: center;">🛠 Build Details</h3>
                            <p style="color: black; font-size: 16px; text-align: center;">
                                <strong>Build Number:</strong> ${env.BUILD_NUMBER}
                            </p>
                            <p style="color: black; font-size: 16px; text-align: center;">
                                <strong>Build Status:</strong> ${currentBuild.result}
                            </p>
                        </div>

                        <div style="background-color: #87CEEB; padding: 20px; margin-bottom: 15px; border-radius: 10px;">
                            <h3 style="color: black; font-weight: bold; text-align: center;">🔗 Build URL</h3>
                            <p style="color: black; font-size: 16px; text-align: center;">
                                <a href="${env.BUILD_URL}" style="color: black; font-weight: bold; text-decoration: none;">
                                    Click Here to View Build Details
                                </a>
                            </p>
                        </div>

                        <div style="background-color: #f4f4f4; padding: 15px; border-top: 2px solid #333;">
                            <p style="color: black; font-size: 14px; text-align: center;">
                                This is an automated email from Jenkins. Please do not reply.
                            </p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'atkaridarshan04@gmail.com',
                mimeType: 'text/html'
            )
        }
    }
  }
}
